name: math_training
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  hydrated_bloc: ^9.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  json_serializable: ^6.7.0
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.15
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/JetBrainsMono-Light.ttf
        - asset: assets/JetBrainsMono-Medium.ttf
          weight: 700